[project]
name = "nekomcp"
version = "0.1.0"
description = "Neko MCP Server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "langchain>=0.3.25",
    "langchain-ollama>=0.3.3",
    "loguru>=0.7.3",
    "mcp[cli]>=1.7.1",
    "streamlit>=1.45.1",
]
